"""
Source Distributions for Flow Matching.

The source distribution supplies :math:`x_0`, the point a trajectory starts
from.  It is the fourth pluggable component of the flow-matching objective,
alongside the path, the time sampler and the coupling.

Making it configurable is what allows the objective to be trained on
*precomputed* pairs rather than freshly drawn noise.  That distinction is the
whole mechanism behind reflow: reflow retrains on pairs
:math:`(z, \\mathrm{ODE}(z))` generated by the current model, and the
straightening only happens if training uses **that** :math:`z` rather than an
independently resampled one.  Drawing fresh noise silently turns reflow into a
no-op.

Available sources:

- :class:`GaussianSource` — standard normal noise (the default).
- :class:`BatchSource` — read :math:`x_0` from the training batch, falling
  back to another source when the key is absent (i.e. at inference time).
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, Tuple, Union

import torch
from torch import Tensor


class SourceDistribution(ABC):
    """
    Abstract base class for flow source distributions.

    A source answers one question: given a target shape and a training batch,
    where does the trajectory start?
    """

    @abstractmethod
    def sample(
        self,
        shape: Tuple[int, ...],
        device: torch.device,
        batch: Optional[Dict[str, Tensor]] = None,
    ) -> Tensor:
        """
        Draw :math:`x_0`.

        Args:
            shape: Shape of the target ``x_1``, which ``x_0`` must match.
            device: Device to place the result on.
            batch: The training batch, when one is available.  Sources that
                read precomputed values use it; others ignore it.

        Returns:
            Tensor of shape ``shape``.
        """
        raise NotImplementedError

    def __call__(
        self,
        shape: Tuple[int, ...],
        device: torch.device,
        batch: Optional[Dict[str, Tensor]] = None,
    ) -> Tensor:
        return self.sample(shape, device, batch)

    def get_config(self) -> Dict[str, Any]:
        return {"type": self.__class__.__name__}


class GaussianSource(SourceDistribution):
    """
    Standard Gaussian source, :math:`x_0 \\sim \\mathcal{N}(0, \\sigma^2 I)`.

    The default for flow matching, and what inference uses regardless of how
    training was configured.

    Args:
        std: Standard deviation (default: 1.0).
    """

    def __init__(self, std: float = 1.0):
        self.std = std

    def sample(
        self,
        shape: Tuple[int, ...],
        device: torch.device,
        batch: Optional[Dict[str, Tensor]] = None,
    ) -> Tensor:
        noise = torch.randn(*shape, device=device)
        return noise * self.std if self.std != 1.0 else noise

    def get_config(self) -> Dict[str, Any]:
        return {"type": "GaussianSource", "std": self.std}

    def __repr__(self) -> str:
        return f"GaussianSource(std={self.std})"


class BatchSource(SourceDistribution):
    """
    Read :math:`x_0` from the training batch.

    Used for reflow, where the pairing between source and target is fixed in
    advance and *must* be preserved: the model is retrained on exactly the
    trajectories it generated, which is what straightens them.

    When the key is absent — most importantly during sampling, where there is
    no batch — the ``fallback`` source is used instead.  So a model trained
    with ``BatchSource`` still samples from :math:`\\mathcal{N}(0, I)` at
    inference, as it should.

    Args:
        key: Batch key holding the precomputed ``x_0`` (default: ``'x_0'``).
        fallback: Source used when the key is missing.  Defaults to
            :class:`GaussianSource`.
        strict: When True, raise instead of falling back if a batch is
            supplied but lacks the key.  Catches silently-degraded reflow
            runs, and is the default for that reason.
    """

    def __init__(
        self,
        key: str = "x_0",
        fallback: Optional[SourceDistribution] = None,
        strict: bool = True,
    ):
        self.key = key
        self.fallback = fallback if fallback is not None else GaussianSource()
        self.strict = strict

    def sample(
        self,
        shape: Tuple[int, ...],
        device: torch.device,
        batch: Optional[Dict[str, Tensor]] = None,
    ) -> Tensor:
        if batch is None:
            # No batch at all: this is inference, so fall back silently.
            return self.fallback.sample(shape, device, batch)

        if self.key not in batch:
            if self.strict:
                available = ", ".join(sorted(batch.keys()))
                raise KeyError(
                    f"BatchSource expected key '{self.key}' in the batch but "
                    f"found only [{available}]. Reflow training must supply "
                    f"the precomputed x_0; resampling noise instead would "
                    f"silently disable path straightening. Pass strict=False "
                    f"to allow falling back to {type(self.fallback).__name__}."
                )
            return self.fallback.sample(shape, device, batch)

        x_0 = batch[self.key]
        x_0 = x_0.flatten(start_dim=1).to(device)

        if x_0.shape != tuple(shape):
            raise ValueError(
                f"Precomputed x_0 has shape {tuple(x_0.shape)} but the target "
                f"requires {tuple(shape)}."
            )
        return x_0

    def get_config(self) -> Dict[str, Any]:
        return {
            "type": "BatchSource",
            "key": self.key,
            "strict": self.strict,
            "fallback": self.fallback.get_config(),
        }

    def __repr__(self) -> str:
        return f"BatchSource(key='{self.key}', fallback={self.fallback!r})"


# =============================================================================
# Factory Function
# =============================================================================

_SOURCE_REGISTRY = {
    "gaussian": GaussianSource,
    "normal": GaussianSource,  # Alias
    "batch": BatchSource,
    "precomputed": BatchSource,  # Alias
}


def get_source(
    source: Union[str, SourceDistribution], **kwargs: Any
) -> SourceDistribution:
    """
    Get a source distribution by name, or pass an instance through.

    Args:
        source: Name (``'gaussian'``, ``'batch'``) or a
            ``SourceDistribution`` instance.
        **kwargs: Forwarded to the constructor when a name is given.

    Returns:
        A ``SourceDistribution``.

    Examples:
        >>> get_source('gaussian')
        GaussianSource(std=1.0)
        >>> isinstance(get_source(GaussianSource()), GaussianSource)
        True
    """
    if isinstance(source, SourceDistribution):
        return source

    if source not in _SOURCE_REGISTRY:
        raise ValueError(
            f"Unknown source: '{source}'. Available: {list(_SOURCE_REGISTRY)}"
        )

    return _SOURCE_REGISTRY[source](**kwargs)
